//
// Copyright © 2020 osy. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// !! THIS FILE IS GENERATED FROM const-gen.py, DO NOT MODIFY MANUALLY !!

#import "UTMConfiguration+Constants.h"

@implementation UTMConfiguration (ConstantsGenerated)

+ (NSArray<NSString *>*)supportedArchitectures {
    return @[
             @"alpha",
             @"arm",
             @"aarch64",
             @"avr",
             @"cris",
             @"hppa",
             @"i386",
             @"lm32",
             @"m68k",
             @"microblaze",
             @"microblazeel",
             @"mips",
             @"mipsel",
             @"mips64",
             @"mips64el",
             @"moxie",
             @"nios2",
             @"or1k",
             @"ppc",
             @"ppc64",
             @"riscv32",
             @"riscv64",
             @"rx",
             @"s390x",
             @"sh4",
             @"sh4eb",
             @"sparc",
             @"sparc64",
             @"tricore",
             @"unicore32",
             @"x86_64",
             @"xtensa",
             @"xtensaeb",
             ];
}

+ (NSArray<NSString *>*)supportedArchitecturesPretty {
    return @[
             @"Alpha",
             @"ARM (aarch32)",
             @"ARM64 (aarch64)",
             @"AVR",
             @"CRIS",
             @"HPPA",
             @"i386 (x86)",
             @"LatticeMico32 (lm32)",
             @"m68k",
             @"Microblaze",
             @"Microblaze (Little Endian)",
             @"MIPS",
             @"MIPS (Little Endian)",
             @"MIPS64",
             @"MIPS64 (Little Endian)",
             @"Moxie",
             @"NIOS2",
             @"OpenRISC",
             @"PowerPC",
             @"PowerPC64",
             @"RISC-V32",
             @"RISC-V64",
             @"RX",
             @"S390x (zSeries)",
             @"SH4",
             @"SH4 (Big Endian)",
             @"SPARC",
             @"SPARC64",
             @"TriCore",
             @"Unicore32",
             @"x86_64",
             @"Xtensa",
             @"Xtensa (Big Endian)",
             ];
}

+ (NSArray<NSString *>*)supportedTargetsForArchitecture:(NSString *)architecture {
    return @{
        @"alpha":
            @[
                @"clipper",
                @"none",
            ],
        @"arm":
            @[
                @"integratorcp",
                @"kzm",
                @"mps2-an385",
                @"mps2-an505",
                @"mps2-an511",
                @"mps2-an521",
                @"musca-a",
                @"musca-b1",
                @"realview-eb-mpcore",
                @"realview-eb",
                @"realview-pbx-a9",
                @"realview-pb-a8",
                @"vexpress-a15",
                @"vexpress-a9",
                @"versatileab",
                @"versatilepb",
                @"imx25-pdk",
                @"ast2500-evb",
                @"ast2600-evb",
                @"microbit",
                @"highbank",
                @"midway",
                @"canon-a1100",
                @"sabrelite",
                @"mcimx6ul-evk",
                @"mcimx7d-sabre",
                @"connex",
                @"verdex",
                @"mainstone",
                @"musicpal",
                @"netduino2",
                @"netduinoplus2",
                @"n800",
                @"n810",
                @"sonorapass-bmc",
                @"palmetto-bmc",
                @"romulus-bmc",
                @"swift-bmc",
                @"tacoma-bmc",
                @"witherspoon-bmc",
                @"orangepi-pc",
                @"cheetah",
                @"virt-2.10",
                @"virt-2.11",
                @"virt-2.12",
                @"virt-2.6",
                @"virt-2.7",
                @"virt-2.8",
                @"virt-2.9",
                @"virt-3.0",
                @"virt-3.1",
                @"virt-4.0",
                @"virt-4.1",
                @"virt-4.2",
                @"virt-5.0",
                @"virt-5.1",
                @"virt",
                @"raspi2",
                @"nuri",
                @"smdkc210",
                @"collie",
                @"tosa",
                @"akita",
                @"spitz",
                @"borzoi",
                @"terrier",
                @"sx1-v1",
                @"sx1",
                @"emcraft-sf2",
                @"lm3s6965evb",
                @"lm3s811evb",
                @"xilinx-zynq-a9",
                @"z2",
                @"cubieboard",
                @"none",
            ],
        @"aarch64":
            @[
                @"integratorcp",
                @"kzm",
                @"mps2-an385",
                @"mps2-an505",
                @"mps2-an511",
                @"mps2-an521",
                @"musca-a",
                @"musca-b1",
                @"realview-eb-mpcore",
                @"realview-eb",
                @"realview-pbx-a9",
                @"realview-pb-a8",
                @"vexpress-a15",
                @"vexpress-a9",
                @"versatileab",
                @"versatilepb",
                @"imx25-pdk",
                @"ast2500-evb",
                @"ast2600-evb",
                @"microbit",
                @"highbank",
                @"midway",
                @"canon-a1100",
                @"sabrelite",
                @"mcimx6ul-evk",
                @"mcimx7d-sabre",
                @"connex",
                @"verdex",
                @"mainstone",
                @"musicpal",
                @"netduino2",
                @"netduinoplus2",
                @"n800",
                @"n810",
                @"sonorapass-bmc",
                @"palmetto-bmc",
                @"romulus-bmc",
                @"swift-bmc",
                @"tacoma-bmc",
                @"witherspoon-bmc",
                @"orangepi-pc",
                @"cheetah",
                @"sbsa-ref",
                @"virt-2.10",
                @"virt-2.11",
                @"virt-2.12",
                @"virt-2.6",
                @"virt-2.7",
                @"virt-2.8",
                @"virt-2.9",
                @"virt-3.0",
                @"virt-3.1",
                @"virt-4.0",
                @"virt-4.1",
                @"virt-4.2",
                @"virt-5.0",
                @"virt-5.1",
                @"virt",
                @"raspi2",
                @"raspi3",
                @"nuri",
                @"smdkc210",
                @"collie",
                @"tosa",
                @"akita",
                @"spitz",
                @"borzoi",
                @"terrier",
                @"sx1-v1",
                @"sx1",
                @"emcraft-sf2",
                @"lm3s6965evb",
                @"lm3s811evb",
                @"xlnx-versal-virt",
                @"xilinx-zynq-a9",
                @"xlnx-zcu102",
                @"z2",
                @"cubieboard",
                @"none",
            ],
        @"avr":
            @[
                @"arduino-duemilanove",
                @"2009",
                @"arduino-mega",
                @"mega",
                @"arduino-mega-2560-v3",
                @"mega2560",
                @"arduino-uno",
                @"uno",
                @"none",
            ],
        @"cris":
            @[
                @"axis-dev88",
                @"none",
            ],
        @"hppa":
            @[
                @"hppa",
                @"none",
            ],
        @"i386":
            @[
                @"isapc",
                @"pc-q35-2.4",
                @"pc-q35-2.6",
                @"pc-q35-2.10",
                @"pc-q35-2.8",
                @"pc-q35-3.0",
                @"pc-q35-4.2",
                @"pc-q35-2.5",
                @"pc-q35-4.1",
                @"pc-q35-3.1",
                @"pc-q35-5.0",
                @"pc-q35-2.12",
                @"pc-q35-5.1",
                @"pc-q35-4.0.1",
                @"pc-q35-4.0",
                @"pc-q35-2.9",
                @"pc-q35-2.7",
                @"pc-q35-2.11",
                @"q35",
                @"pc-i440fx-2.4",
                @"pc-i440fx-1.4",
                @"pc-i440fx-4.0",
                @"pc-i440fx-2.5",
                @"pc-i440fx-2.0",
                @"pc-i440fx-4.1",
                @"pc-i440fx-2.6",
                @"pc-i440fx-3.1",
                @"pc-i440fx-2.1",
                @"pc-i440fx-2.7",
                @"pc-i440fx-2.10",
                @"pc-i440fx-1.7",
                @"pc-i440fx-3.0",
                @"pc-i440fx-5.0",
                @"pc-i440fx-2.2",
                @"pc-i440fx-1.6",
                @"pc-i440fx-2.8",
                @"pc-i440fx-1.5",
                @"pc-i440fx-2.11",
                @"pc-i440fx-4.2",
                @"pc-i440fx-2.3",
                @"pc-i440fx-2.9",
                @"pc-i440fx-2.12",
                @"pc",
                @"pc-i440fx-5.1",
                @"pc-1.1",
                @"pc-1.3",
                @"pc-1.0",
                @"pc-1.2",
                @"none",
                @"microvm",
            ],
        @"lm32":
            @[
                @"lm32-evr",
                @"milkymist",
                @"none",
                @"lm32-uclinux",
            ],
        @"m68k":
            @[
                @"an5206",
                @"mcf5208evb",
                @"q800",
                @"next-cube",
                @"none",
            ],
        @"microblaze":
            @[
                @"petalogix-s3adsp1800",
                @"petalogix-ml605",
                @"xlnx-zynqmp-pmu",
                @"none",
            ],
        @"microblazeel":
            @[
                @"petalogix-s3adsp1800",
                @"petalogix-ml605",
                @"xlnx-zynqmp-pmu",
                @"none",
            ],
        @"mips":
            @[
                @"mipssim",
                @"malta",
                @"none",
                @"mips",
            ],
        @"mipsel":
            @[
                @"mipssim",
                @"malta",
                @"none",
                @"mips",
            ],
        @"mips64":
            @[
                @"pica61",
                @"mipssim",
                @"magnum",
                @"malta",
                @"none",
                @"mips",
            ],
        @"mips64el":
            @[
                @"pica61",
                @"fuloong2e",
                @"fulong2e",
                @"boston",
                @"mipssim",
                @"magnum",
                @"malta",
                @"none",
                @"mips",
            ],
        @"moxie":
            @[
                @"moxiesim",
                @"none",
            ],
        @"nios2":
            @[
                @"10m50-ghrd",
                @"nios2-generic-nommu",
                @"none",
            ],
        @"or1k":
            @[
                @"none",
                @"or1k-sim",
            ],
        @"ppc":
            @[
                @"g3beige",
                @"40p",
                @"mac99",
                @"virtex-ml507",
                @"sam460ex",
                @"bamboo",
                @"none",
                @"ppce500",
                @"mpc8544ds",
                @"ref405ep",
                @"taihu",
            ],
        @"ppc64":
            @[
                @"g3beige",
                @"powernv10",
                @"powernv8",
                @"powernv9",
                @"powernv",
                @"40p",
                @"mac99",
                @"virtex-ml507",
                @"sam460ex",
                @"bamboo",
                @"none",
                @"ppce500",
                @"mpc8544ds",
                @"pseries-4.2",
                @"pseries-2.9",
                @"pseries-2.6",
                @"pseries-2.5",
                @"pseries-4.0",
                @"pseries-5.0",
                @"pseries-2.7",
                @"pseries-3.0",
                @"pseries-4.1",
                @"pseries-2.12",
                @"pseries-2.1",
                @"pseries-2.8",
                @"pseries-2.4",
                @"pseries-3.1",
                @"pseries-2.2",
                @"pseries-2.12-sxxm",
                @"pseries-2.11",
                @"pseries-2.3",
                @"pseries-2.10",
                @"pseries",
                @"pseries-5.1",
                @"ref405ep",
                @"taihu",
            ],
        @"riscv32":
            @[
                @"opentitan",
                @"sifive_e",
                @"sifive_u",
                @"spike",
                @"virt",
                @"none",
            ],
        @"riscv64":
            @[
                @"sifive_e",
                @"sifive_u",
                @"spike",
                @"virt",
                @"none",
            ],
        @"rx":
            @[
                @"none",
                @"gdbsim-r5f562n7",
                @"gdbsim-r5f562n8",
            ],
        @"s390x":
            @[
                @"s390-ccw-virtio-2.10",
                @"s390-ccw-virtio-2.11",
                @"s390-ccw-virtio-2.12",
                @"s390-ccw-virtio-2.4",
                @"s390-ccw-virtio-2.5",
                @"s390-ccw-virtio-2.6",
                @"s390-ccw-virtio-2.7",
                @"s390-ccw-virtio-2.8",
                @"s390-ccw-virtio-2.9",
                @"s390-ccw-virtio-3.0",
                @"s390-ccw-virtio-3.1",
                @"s390-ccw-virtio-4.0",
                @"s390-ccw-virtio-4.1",
                @"s390-ccw-virtio-4.2",
                @"s390-ccw-virtio-5.0",
                @"s390-ccw-virtio",
                @"s390-ccw-virtio-5.1",
                @"none",
            ],
        @"sh4":
            @[
                @"none",
                @"r2d",
                @"shix",
            ],
        @"sh4eb":
            @[
                @"none",
                @"r2d",
                @"shix",
            ],
        @"sparc":
            @[
                @"leon3_generic",
                @"SPARCClassic",
                @"SPARCbook",
                @"SS-600MP",
                @"SS-10",
                @"SS-20",
                @"SS-4",
                @"SS-5",
                @"LX",
                @"Voyager",
                @"none",
            ],
        @"sparc64":
            @[
                @"sun4u",
                @"sun4v",
                @"niagara",
                @"none",
            ],
        @"tricore":
            @[
                @"tricore_testboard",
                @"none",
            ],
        @"unicore32":
            @[
                @"puv3",
                @"none",
            ],
        @"x86_64":
            @[
                @"isapc",
                @"pc-q35-2.4",
                @"pc-q35-2.6",
                @"pc-q35-2.10",
                @"pc-q35-2.8",
                @"pc-q35-3.0",
                @"pc-q35-4.2",
                @"pc-q35-2.5",
                @"pc-q35-4.1",
                @"pc-q35-3.1",
                @"pc-q35-5.0",
                @"pc-q35-2.12",
                @"pc-q35-5.1",
                @"pc-q35-4.0.1",
                @"pc-q35-4.0",
                @"pc-q35-2.9",
                @"pc-q35-2.7",
                @"pc-q35-2.11",
                @"q35",
                @"pc-i440fx-2.4",
                @"pc-i440fx-1.4",
                @"pc-i440fx-4.0",
                @"pc-i440fx-2.5",
                @"pc-i440fx-2.0",
                @"pc-i440fx-4.1",
                @"pc-i440fx-2.6",
                @"pc-i440fx-3.1",
                @"pc-i440fx-2.1",
                @"pc-i440fx-2.7",
                @"pc-i440fx-2.10",
                @"pc-i440fx-1.7",
                @"pc-i440fx-3.0",
                @"pc-i440fx-5.0",
                @"pc-i440fx-2.2",
                @"pc-i440fx-1.6",
                @"pc-i440fx-2.8",
                @"pc-i440fx-1.5",
                @"pc-i440fx-2.11",
                @"pc-i440fx-4.2",
                @"pc-i440fx-2.3",
                @"pc-i440fx-2.9",
                @"pc-i440fx-2.12",
                @"pc",
                @"pc-i440fx-5.1",
                @"pc-1.1",
                @"pc-1.3",
                @"pc-1.0",
                @"pc-1.2",
                @"none",
                @"microvm",
            ],
        @"xtensa":
            @[
                @"none",
                @"kc705",
                @"kc705-nommu",
                @"lx200",
                @"lx200-nommu",
                @"lx60",
                @"lx60-nommu",
                @"ml605",
                @"ml605-nommu",
                @"sim",
                @"virt",
            ],
        @"xtensaeb":
            @[
                @"none",
                @"kc705",
                @"kc705-nommu",
                @"lx200",
                @"lx200-nommu",
                @"lx60",
                @"lx60-nommu",
                @"ml605",
                @"ml605-nommu",
                @"sim",
                @"virt",
            ],
    }[architecture];
}

+ (NSArray<NSString *>*)supportedTargetsForArchitecturePretty:(NSString *)architecture {
    return @{
        @"alpha":
            @[
                @"Alpha DP264/CLIPPER (default)",
                @"empty machine",
            ],
        @"arm":
            @[
                @"ARM Integrator/CP (ARM926EJ-S)",
                @"ARM KZM Emulation Baseboard (ARM1136)",
                @"ARM MPS2 with AN385 FPGA image for Cortex-M3",
                @"ARM MPS2 with AN505 FPGA image for Cortex-M33",
                @"ARM MPS2 with AN511 DesignStart FPGA image for Cortex-M3",
                @"ARM MPS2 with AN521 FPGA image for dual Cortex-M33",
                @"ARM Musca-A board (dual Cortex-M33)",
                @"ARM Musca-B1 board (dual Cortex-M33)",
                @"ARM RealView Emulation Baseboard (ARM11MPCore)",
                @"ARM RealView Emulation Baseboard (ARM926EJ-S)",
                @"ARM RealView Platform Baseboard Explore for Cortex-A9",
                @"ARM RealView Platform Baseboard for Cortex-A8",
                @"ARM Versatile Express for Cortex-A15",
                @"ARM Versatile Express for Cortex-A9",
                @"ARM Versatile/AB (ARM926EJ-S)",
                @"ARM Versatile/PB (ARM926EJ-S)",
                @"ARM i.MX25 PDK board (ARM926)",
                @"Aspeed AST2500 EVB (ARM1176)",
                @"Aspeed AST2600 EVB (Cortex A7)",
                @"BBC micro:bit",
                @"Calxeda Highbank (ECX-1000)",
                @"Calxeda Midway (ECX-2000)",
                @"Canon PowerShot A1100 IS",
                @"Freescale i.MX6 Quad SABRE Lite Board (Cortex A9)",
                @"Freescale i.MX6UL Evaluation Kit (Cortex A7)",
                @"Freescale i.MX7 DUAL SABRE (Cortex A7)",
                @"Gumstix Connex (PXA255)",
                @"Gumstix Verdex (PXA270)",
                @"Mainstone II (PXA27x)",
                @"Marvell 88w8618 / MusicPal (ARM926EJ-S)",
                @"Netduino 2 Machine",
                @"Netduino Plus 2 Machine",
                @"Nokia N800 tablet aka. RX-34 (OMAP2420)",
                @"Nokia N810 tablet aka. RX-44 (OMAP2420)",
                @"OCP SonoraPass BMC (ARM1176)",
                @"OpenPOWER Palmetto BMC (ARM926EJ-S)",
                @"OpenPOWER Romulus BMC (ARM1176)",
                @"OpenPOWER Swift BMC (ARM1176)",
                @"OpenPOWER Tacoma BMC (Cortex A7)",
                @"OpenPOWER Witherspoon BMC (ARM1176)",
                @"Orange Pi PC",
                @"Palm Tungsten|E aka. Cheetah PDA (OMAP310)",
                @"QEMU 2.10 ARM Virtual Machine",
                @"QEMU 2.11 ARM Virtual Machine",
                @"QEMU 2.12 ARM Virtual Machine",
                @"QEMU 2.6 ARM Virtual Machine",
                @"QEMU 2.7 ARM Virtual Machine",
                @"QEMU 2.8 ARM Virtual Machine",
                @"QEMU 2.9 ARM Virtual Machine",
                @"QEMU 3.0 ARM Virtual Machine",
                @"QEMU 3.1 ARM Virtual Machine",
                @"QEMU 4.0 ARM Virtual Machine",
                @"QEMU 4.1 ARM Virtual Machine",
                @"QEMU 4.2 ARM Virtual Machine",
                @"QEMU 5.0 ARM Virtual Machine",
                @"QEMU 5.1 ARM Virtual Machine",
                @"QEMU 5.1 ARM Virtual Machine (alias of virt-5.1)",
                @"Raspberry Pi 2B",
                @"Samsung NURI board (Exynos4210)",
                @"Samsung SMDKC210 board (Exynos4210)",
                @"Sharp SL-5500 (Collie) PDA (SA-1110)",
                @"Sharp SL-6000 (Tosa) PDA (PXA255)",
                @"Sharp SL-C1000 (Akita) PDA (PXA270)",
                @"Sharp SL-C3000 (Spitz) PDA (PXA270)",
                @"Sharp SL-C3100 (Borzoi) PDA (PXA270)",
                @"Sharp SL-C3200 (Terrier) PDA (PXA270)",
                @"Siemens SX1 (OMAP310) V1",
                @"Siemens SX1 (OMAP310) V2",
                @"SmartFusion2 SOM kit from Emcraft (M2S010)",
                @"Stellaris LM3S6965EVB",
                @"Stellaris LM3S811EVB",
                @"Xilinx Zynq Platform Baseboard for Cortex-A9",
                @"Zipit Z2 (PXA27x)",
                @"cubietech cubieboard (Cortex-A8)",
                @"empty machine",
            ],
        @"aarch64":
            @[
                @"ARM Integrator/CP (ARM926EJ-S)",
                @"ARM KZM Emulation Baseboard (ARM1136)",
                @"ARM MPS2 with AN385 FPGA image for Cortex-M3",
                @"ARM MPS2 with AN505 FPGA image for Cortex-M33",
                @"ARM MPS2 with AN511 DesignStart FPGA image for Cortex-M3",
                @"ARM MPS2 with AN521 FPGA image for dual Cortex-M33",
                @"ARM Musca-A board (dual Cortex-M33)",
                @"ARM Musca-B1 board (dual Cortex-M33)",
                @"ARM RealView Emulation Baseboard (ARM11MPCore)",
                @"ARM RealView Emulation Baseboard (ARM926EJ-S)",
                @"ARM RealView Platform Baseboard Explore for Cortex-A9",
                @"ARM RealView Platform Baseboard for Cortex-A8",
                @"ARM Versatile Express for Cortex-A15",
                @"ARM Versatile Express for Cortex-A9",
                @"ARM Versatile/AB (ARM926EJ-S)",
                @"ARM Versatile/PB (ARM926EJ-S)",
                @"ARM i.MX25 PDK board (ARM926)",
                @"Aspeed AST2500 EVB (ARM1176)",
                @"Aspeed AST2600 EVB (Cortex A7)",
                @"BBC micro:bit",
                @"Calxeda Highbank (ECX-1000)",
                @"Calxeda Midway (ECX-2000)",
                @"Canon PowerShot A1100 IS",
                @"Freescale i.MX6 Quad SABRE Lite Board (Cortex A9)",
                @"Freescale i.MX6UL Evaluation Kit (Cortex A7)",
                @"Freescale i.MX7 DUAL SABRE (Cortex A7)",
                @"Gumstix Connex (PXA255)",
                @"Gumstix Verdex (PXA270)",
                @"Mainstone II (PXA27x)",
                @"Marvell 88w8618 / MusicPal (ARM926EJ-S)",
                @"Netduino 2 Machine",
                @"Netduino Plus 2 Machine",
                @"Nokia N800 tablet aka. RX-34 (OMAP2420)",
                @"Nokia N810 tablet aka. RX-44 (OMAP2420)",
                @"OCP SonoraPass BMC (ARM1176)",
                @"OpenPOWER Palmetto BMC (ARM926EJ-S)",
                @"OpenPOWER Romulus BMC (ARM1176)",
                @"OpenPOWER Swift BMC (ARM1176)",
                @"OpenPOWER Tacoma BMC (Cortex A7)",
                @"OpenPOWER Witherspoon BMC (ARM1176)",
                @"Orange Pi PC",
                @"Palm Tungsten|E aka. Cheetah PDA (OMAP310)",
                @"QEMU 'SBSA Reference' ARM Virtual Machine",
                @"QEMU 2.10 ARM Virtual Machine",
                @"QEMU 2.11 ARM Virtual Machine",
                @"QEMU 2.12 ARM Virtual Machine",
                @"QEMU 2.6 ARM Virtual Machine",
                @"QEMU 2.7 ARM Virtual Machine",
                @"QEMU 2.8 ARM Virtual Machine",
                @"QEMU 2.9 ARM Virtual Machine",
                @"QEMU 3.0 ARM Virtual Machine",
                @"QEMU 3.1 ARM Virtual Machine",
                @"QEMU 4.0 ARM Virtual Machine",
                @"QEMU 4.1 ARM Virtual Machine",
                @"QEMU 4.2 ARM Virtual Machine",
                @"QEMU 5.0 ARM Virtual Machine",
                @"QEMU 5.1 ARM Virtual Machine",
                @"QEMU 5.1 ARM Virtual Machine (alias of virt-5.1)",
                @"Raspberry Pi 2B",
                @"Raspberry Pi 3B",
                @"Samsung NURI board (Exynos4210)",
                @"Samsung SMDKC210 board (Exynos4210)",
                @"Sharp SL-5500 (Collie) PDA (SA-1110)",
                @"Sharp SL-6000 (Tosa) PDA (PXA255)",
                @"Sharp SL-C1000 (Akita) PDA (PXA270)",
                @"Sharp SL-C3000 (Spitz) PDA (PXA270)",
                @"Sharp SL-C3100 (Borzoi) PDA (PXA270)",
                @"Sharp SL-C3200 (Terrier) PDA (PXA270)",
                @"Siemens SX1 (OMAP310) V1",
                @"Siemens SX1 (OMAP310) V2",
                @"SmartFusion2 SOM kit from Emcraft (M2S010)",
                @"Stellaris LM3S6965EVB",
                @"Stellaris LM3S811EVB",
                @"Xilinx Versal Virtual development board",
                @"Xilinx Zynq Platform Baseboard for Cortex-A9",
                @"Xilinx ZynqMP ZCU102 board with 4xA53s and 2xR5Fs based on the value of smp",
                @"Zipit Z2 (PXA27x)",
                @"cubietech cubieboard (Cortex-A8)",
                @"empty machine",
            ],
        @"avr":
            @[
                @"Arduino Duemilanove (ATmega168)",
                @"Arduino Duemilanove (ATmega168) (alias of arduino-duemilanove)",
                @"Arduino Mega (ATmega1280)",
                @"Arduino Mega (ATmega1280) (alias of arduino-mega)",
                @"Arduino Mega 2560 (ATmega2560)",
                @"Arduino Mega 2560 (ATmega2560) (alias of arduino-mega-2560-v3)",
                @"Arduino UNO (ATmega328P)",
                @"Arduino UNO (ATmega328P) (alias of arduino-uno)",
                @"empty machine",
            ],
        @"cris":
            @[
                @"AXIS devboard 88 (default)",
                @"empty machine",
            ],
        @"hppa":
            @[
                @"HPPA generic machine (default)",
                @"empty machine",
            ],
        @"i386":
            @[
                @"ISA-only PC",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009) (alias of pc-q35-5.1)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996) (alias of pc-i440fx-5.1)",
                @"Standard PC (i440FX + PIIX, 1996) (default)",
                @"Standard PC (i440FX + PIIX, 1996) (deprecated)",
                @"Standard PC (i440FX + PIIX, 1996) (deprecated)",
                @"Standard PC (i440FX + PIIX, 1996) (deprecated)",
                @"Standard PC (i440FX + PIIX, 1996) (deprecated)",
                @"empty machine",
                @"microvm (i386)",
            ],
        @"lm32":
            @[
                @"LatticeMico32 EVR32 eval system (default)",
                @"Milkymist One",
                @"empty machine",
                @"lm32 platform for uClinux and u-boot by Theobroma Systems",
            ],
        @"m68k":
            @[
                @"Arnewsh 5206",
                @"MCF5208EVB (default)",
                @"Macintosh Quadra 800",
                @"NeXT Cube",
                @"empty machine",
            ],
        @"microblaze":
            @[
                @"PetaLogix linux refdesign for xilinx Spartan 3ADSP1800 (default)",
                @"PetaLogix linux refdesign for xilinx ml605 little endian",
                @"Xilinx ZynqMP PMU machine",
                @"empty machine",
            ],
        @"microblazeel":
            @[
                @"PetaLogix linux refdesign for xilinx Spartan 3ADSP1800 (default)",
                @"PetaLogix linux refdesign for xilinx ml605 little endian",
                @"Xilinx ZynqMP PMU machine",
                @"empty machine",
            ],
        @"mips":
            @[
                @"MIPS MIPSsim platform",
                @"MIPS Malta Core LV (default)",
                @"empty machine",
                @"mips r4k platform (deprecated)",
            ],
        @"mipsel":
            @[
                @"MIPS MIPSsim platform",
                @"MIPS Malta Core LV (default)",
                @"empty machine",
                @"mips r4k platform (deprecated)",
            ],
        @"mips64":
            @[
                @"Acer Pica 61",
                @"MIPS MIPSsim platform",
                @"MIPS Magnum",
                @"MIPS Malta Core LV (default)",
                @"empty machine",
                @"mips r4k platform (deprecated)",
            ],
        @"mips64el":
            @[
                @"Acer Pica 61",
                @"Fuloong 2e mini pc",
                @"Fuloong 2e mini pc (alias of fuloong2e)",
                @"MIPS Boston",
                @"MIPS MIPSsim platform",
                @"MIPS Magnum",
                @"MIPS Malta Core LV (default)",
                @"empty machine",
                @"mips r4k platform (deprecated)",
            ],
        @"moxie":
            @[
                @"Moxie simulator platform (default)",
                @"empty machine",
            ],
        @"nios2":
            @[
                @"Altera 10M50 GHRD Nios II design (default)",
                @"Generic NOMMU Nios II design",
                @"empty machine",
            ],
        @"or1k":
            @[
                @"empty machine",
                @"or1k simulation (default)",
            ],
        @"ppc":
            @[
                @"Heathrow based PowerMAC (default)",
                @"IBM RS/6000 7020 (40p)",
                @"Mac99 based PowerMAC",
                @"Xilinx Virtex ML507 reference design",
                @"aCube Sam460ex",
                @"bamboo",
                @"empty machine",
                @"generic paravirt e500 platform",
                @"mpc8544ds",
                @"ref405ep",
                @"taihu",
            ],
        @"ppc64":
            @[
                @"Heathrow based PowerMAC",
                @"IBM PowerNV (Non-Virtualized) POWER10",
                @"IBM PowerNV (Non-Virtualized) POWER8",
                @"IBM PowerNV (Non-Virtualized) POWER9",
                @"IBM PowerNV (Non-Virtualized) POWER9 (alias of powernv9)",
                @"IBM RS/6000 7020 (40p)",
                @"Mac99 based PowerMAC",
                @"Xilinx Virtex ML507 reference design",
                @"aCube Sam460ex",
                @"bamboo",
                @"empty machine",
                @"generic paravirt e500 platform",
                @"mpc8544ds",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant)",
                @"pSeries Logical Partition (PAPR compliant) (alias of pseries-5.1)",
                @"pSeries Logical Partition (PAPR compliant) (default)",
                @"ref405ep",
                @"taihu",
            ],
        @"riscv32":
            @[
                @"RISC-V Board compatible with OpenTitan",
                @"RISC-V Board compatible with SiFive E SDK",
                @"RISC-V Board compatible with SiFive U SDK",
                @"RISC-V Spike Board (default)",
                @"RISC-V VirtIO board",
                @"empty machine",
            ],
        @"riscv64":
            @[
                @"RISC-V Board compatible with SiFive E SDK",
                @"RISC-V Board compatible with SiFive U SDK",
                @"RISC-V Spike Board (default)",
                @"RISC-V VirtIO board",
                @"empty machine",
            ],
        @"rx":
            @[
                @"empty machine",
                @"gdb simulator (R5F562N7 MCU and external RAM)",
                @"gdb simulator (R5F562N8 MCU and external RAM)",
            ],
        @"s390x":
            @[
                @"VirtIO-ccw based S390 machine v2.10",
                @"VirtIO-ccw based S390 machine v2.11",
                @"VirtIO-ccw based S390 machine v2.12",
                @"VirtIO-ccw based S390 machine v2.4",
                @"VirtIO-ccw based S390 machine v2.5",
                @"VirtIO-ccw based S390 machine v2.6",
                @"VirtIO-ccw based S390 machine v2.7",
                @"VirtIO-ccw based S390 machine v2.8",
                @"VirtIO-ccw based S390 machine v2.9",
                @"VirtIO-ccw based S390 machine v3.0",
                @"VirtIO-ccw based S390 machine v3.1",
                @"VirtIO-ccw based S390 machine v4.0",
                @"VirtIO-ccw based S390 machine v4.1",
                @"VirtIO-ccw based S390 machine v4.2",
                @"VirtIO-ccw based S390 machine v5.0",
                @"VirtIO-ccw based S390 machine v5.1 (alias of s390-ccw-virtio-5.1)",
                @"VirtIO-ccw based S390 machine v5.1 (default)",
                @"empty machine",
            ],
        @"sh4":
            @[
                @"empty machine",
                @"r2d-plus board",
                @"shix card (default)",
            ],
        @"sh4eb":
            @[
                @"empty machine",
                @"r2d-plus board",
                @"shix card (default)",
            ],
        @"sparc":
            @[
                @"Leon-3 generic",
                @"Sun4m platform, SPARCClassic",
                @"Sun4m platform, SPARCbook",
                @"Sun4m platform, SPARCserver 600MP",
                @"Sun4m platform, SPARCstation 10",
                @"Sun4m platform, SPARCstation 20",
                @"Sun4m platform, SPARCstation 4",
                @"Sun4m platform, SPARCstation 5 (default)",
                @"Sun4m platform, SPARCstation LX",
                @"Sun4m platform, SPARCstation Voyager",
                @"empty machine",
            ],
        @"sparc64":
            @[
                @"Sun4u platform (default)",
                @"Sun4v platform",
                @"Sun4v platform, Niagara",
                @"empty machine",
            ],
        @"tricore":
            @[
                @"a minimal TriCore board",
                @"empty machine",
            ],
        @"unicore32":
            @[
                @"PKUnity Version-3 based on UniCore32 (default)",
                @"empty machine",
            ],
        @"x86_64":
            @[
                @"ISA-only PC",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009)",
                @"Standard PC (Q35 + ICH9, 2009) (alias of pc-q35-5.1)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996)",
                @"Standard PC (i440FX + PIIX, 1996) (alias of pc-i440fx-5.1)",
                @"Standard PC (i440FX + PIIX, 1996) (default)",
                @"Standard PC (i440FX + PIIX, 1996) (deprecated)",
                @"Standard PC (i440FX + PIIX, 1996) (deprecated)",
                @"Standard PC (i440FX + PIIX, 1996) (deprecated)",
                @"Standard PC (i440FX + PIIX, 1996) (deprecated)",
                @"empty machine",
                @"microvm (i386)",
            ],
        @"xtensa":
            @[
                @"empty machine",
                @"kc705 EVB (dc232b)",
                @"kc705 noMMU EVB (de212)",
                @"lx200 EVB (dc232b)",
                @"lx200 noMMU EVB (de212)",
                @"lx60 EVB (dc232b)",
                @"lx60 noMMU EVB (de212)",
                @"ml605 EVB (dc232b)",
                @"ml605 noMMU EVB (de212)",
                @"sim machine (dc232b) (default)",
                @"virt machine (dc232b)",
            ],
        @"xtensaeb":
            @[
                @"empty machine",
                @"kc705 EVB (fsf)",
                @"kc705 noMMU EVB (fsf)",
                @"lx200 EVB (fsf)",
                @"lx200 noMMU EVB (fsf)",
                @"lx60 EVB (fsf)",
                @"lx60 noMMU EVB (fsf)",
                @"ml605 EVB (fsf)",
                @"ml605 noMMU EVB (fsf)",
                @"sim machine (fsf) (default)",
                @"virt machine (fsf)",
            ],
    }[architecture];
}

+ (NSInteger)defaultTargetIndexForArchitecture:(NSString *)architecture {
    return [@{
        @"alpha": @0,
        @"arm": @56,
        @"aarch64": @57,
        @"avr": @3,
        @"cris": @0,
        @"hppa": @0,
        @"i386": @42,
        @"lm32": @0,
        @"m68k": @1,
        @"microblaze": @0,
        @"microblazeel": @0,
        @"mips": @1,
        @"mipsel": @1,
        @"mips64": @3,
        @"mips64el": @6,
        @"moxie": @0,
        @"nios2": @0,
        @"or1k": @1,
        @"ppc": @0,
        @"ppc64": @33,
        @"riscv32": @3,
        @"riscv64": @2,
        @"rx": @1,
        @"s390x": @16,
        @"sh4": @2,
        @"sh4eb": @2,
        @"sparc": @7,
        @"sparc64": @0,
        @"tricore": @0,
        @"unicore32": @0,
        @"x86_64": @42,
        @"xtensa": @9,
        @"xtensaeb": @9,
    }[architecture] integerValue];
}

+ (NSArray<NSString *>*)supportedNetworkCards {
    return @[
             @"e1000e",
             @"e1000-82544gc",
             @"e1000-82545em",
             @"e1000",
             @"i82550",
             @"i82551",
             @"i82557a",
             @"i82557b",
             @"i82557c",
             @"i82558a",
             @"i82558b",
             @"i82559a",
             @"i82559b",
             @"i82559c",
             @"i82559er",
             @"i82562",
             @"i82801",
             @"VT82C686B_MC97",
             @"rocker",
             @"vmxnet3",
             @"ne2k_isa",
             @"ne2k_pci",
             @"pcnet",
             @"rtl8139",
             @"spapr-vlan",
             @"sungem",
             @"sunhme",
             @"tulip",
             @"usb-net",
             @"virtio-net-ccw",
             @"virtio-net-device",
             @"virtio-net-pci",
             @"virtio-net-pci",
             @"virtio-net-pci-non-transitional",
             @"virtio-net-pci-transitional",
             ];
}

+ (NSArray<NSString *>*)supportedNetworkCardsPretty {
    return @[
             @"Intel 82574L GbE Controller",
             @"Intel Gigabit Ethernet",
             @"Intel Gigabit Ethernet",
             @"Intel Gigabit Ethernet",
             @"Intel i82550 Ethernet",
             @"Intel i82551 Ethernet",
             @"Intel i82557A Ethernet",
             @"Intel i82557B Ethernet",
             @"Intel i82557C Ethernet",
             @"Intel i82558A Ethernet",
             @"Intel i82558B Ethernet",
             @"Intel i82559A Ethernet",
             @"Intel i82559B Ethernet",
             @"Intel i82559C Ethernet",
             @"Intel i82559ER Ethernet",
             @"Intel i82562 Ethernet",
             @"Intel i82801 Ethernet",
             @"MC97",
             @"Rocker Switch",
             @"VMWare Paravirtualized Ethernet v3",
             @"None",
             @"None",
             @"None",
             @"None",
             @"None",
             @"None",
             @"None",
             @"None",
             @"None",
             @"None",
             @"None",
             @"None",
             @"None",
             @"None",
             @"None",
             ];
}

+ (NSArray<NSString *>*)supportedSoundCardDevices {
    return @[
             @"cs4231a",
             @"sb16",
             @"es1370",
             @"gus",
             @"ac97",
             @"hda",
             @"pcspk",
             @"adlib",
             ];
}

+ (NSArray<NSString *>*)supportedSoundCardDevicesPretty {
    return @[
             @"CS4231A",
             @"Creative Sound Blaster 16",
             @"ENSONIQ AudioPCI ES1370",
             @"Gravis Ultrasound GF1",
             @"Intel 82801AA AC97 Audio",
             @"Intel HD Audio",
             @"PC speaker",
             @"Yamaha YM3812 (OPL2)",
             ];
}

@end
